### PR TITLE
Skip section folder if not a single plane can be loaded

### PR DESCRIPTION
**Pull request by ablot**
If there is no tileIndex, no data can be loaded but no error was
returned by load_imstack in preProcessTiles. Add a test for empty
imStack

### CODE REVIEW

**Comment by raacampbell** [comment]
OK, I can just delete the commented-out lines in `preProcessTiles`, yes?

**Comment by ablot** [comment]
yes. I kept them just on case you wanted to revert something

**Comment by raacampbell** [comment]
What are we doing here? I forgot.

**Comment by ablot** [comment]
I think that was resolved by some of the changes in #83. I'll close for now and see if it  re-appears :)

**Pull request closed without merging**
