### PR TITLE
Added to IlluminationCorrector option with cidre

### PR DESCRIPTION
**Pull request by Fouga**
It checks if in averDir exist .mat file with defined fields.

### CODE REVIEW

**Comment by raacampbell** [comment]
Thanks. Can you modify `cidreIllumcorrection` so it only calculates what is needed for the cidre correction and nothing else? It it currently stitches. And also do doc text for it.

**Comment by Fouga** [comment]
Modified. Should I pull it to you?

**Comment by raacampbell** [comment]
Good, nearly there. 

* Did you make the doc text for `cidreIllumcorrection.m` ? 
* I think you said that you have modified cidre in some way to allow this to work? We'll need that fork accesible so we can point people to it in the README. In fact, `cidreIllumcorrection.m` could even check to see it exists before attempting to run. We need to make it easy for the user. 
* We need to future-proof where you check for MAT files in `illuminationCorrector`. I'm not sure what's going on there right now because I can't immediately see check_cidreModel. If we don't do this now, we will run into problems later if we add a different illumination correction file format. To confirm, the sequence needs to be: 1) If there's a MAT file then load it. 2) The MAT file should be a structure that contains whatever the illumination correction needs plus a field with a name like `type` that we can set to 'cidre' or whatever. Then we can can have switch statement that will call the correct illumination routine for the MAT file. 3) If it's not a MAT file carry on with whatever was done before. 

* I see in cidreIllumcorrection.m  you have a line that reads `source = sprintf('./rawData/*_0%i.tif',thisChan);` How does that work? There are no TIFF files directly under `rawData`.

**Comment by Fouga** [comment]
1. I did not make doc file. Can you send me a template...?
2. Can you see this https://github.com/Fouga/cidre/tree/dev ? In a folder dependencies you can find check_cidreModel.
3. you can see in cidre function. It still uses rdir.

**Comment by raacampbell** [comment]
1. I don't mean a separate doc file. I mean document your function `cidreIllumcorrection.m` with help text. e.g. compare [this](https://github.com/Fouga/StitchIt/blob/dev/code/processDuringAcquistion/cidreIllumcorrection.m) with the doc text [here](https://github.com/Fouga/StitchIt/blob/dev/code/utils/handleSectionArg.m) or [here](https://github.com/Fouga/StitchIt/blob/dev/code/processDuringAcquistion/estimateEndTime.m). So an [H1 line](https://ch.mathworks.com/help/matlab/matlab_prog/add-help-for-your-program.html), what the function does, what its arguments are, references to other similar functions, etc.

2. People who don't use cidre will have `tileLoad` crash because they don't have `check_cidreModel` in their path. We only want to call cidre-related functions if the user has already created cidre average tiles. Otherwise everyone has to add cidre to their path even if they don't use it. So the pseudo-code should be:
```
  IF FORMAT_OF_AVERAGE_FILES == '.mat'
      LOAD .mat  %we agree on a variable name for them, e.g. "illumData", which is a structure. I wouldn't use "model_def", it's too vague.
      SWITCH illumData.type
         CASE 'cidre'
              %do cidre things. Here it's ok to put in the name of a function not in everyone's path
         CASE 'somethingElse'
              %do somethingElse
        OTHERWISE
              DO NOTHING AND RETURN RAW TILES
        END
   ELSE
       run the existing stuff
   END
```


3. I see... It splits it up.

**Pull request closed without merging**
